language: c
compiler: gcc
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq gnome-common libglib2.0-dev gobject-introspection
    gtk-doc-tools libgudev-1.0-dev libpolkit-gobject-1-dev
    libpolkit-agent-1-dev dbus cups-filters
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script: ./autogen.sh --disable-systemd &&
        DISPLAY=:99.0 make distcheck
        DISTCHECK_CONFIGURE_FLAGS="--disable-introspection --disable-systemd"
        TESTS_ENVIRONMENT='$(MAKE) -s printerd-session.pid;top_srcdir=$(top_srcdir) top_builddir=$(top_builddir) BOOKMARK=$(TEST_BOOKMARK) SESSION_LOG=$(TEST_SESSION_LOG)'
